---
kind: pipeline
name: default

workspace:
  base: /go
  path: src/github.com/graphite-ng/carbon-relay-ng

platform:
  os: linux
  arch: amd64

steps:
- name: test
  image: golang:1.10
  commands:
  - go test -v -race ./...

- name: build
  image: golang:1.10
  commands:
  - go get github.com/shuLhan/go-bindata/cmd/go-bindata
  - make build-linux

#- name: github-release
#  image: plugins/github-release
#  settings:
#    files: "target/scala*/jvm-csdl-util.jar"
#    prerelease: true
#  environment:
#    GITHUB_TOKEN:
#      from_secret: github_token
#  when:
#    event:
#    - tag
